<?php
function pathautoalter_pathauto_punctuation_chars_alter(&$punctuation) {
    $punctuation['double_curly_left']  = array('value' => '“', 'name' => t('Double curly left'));
    $punctuation['double_curly_right'] = array('value' => '”', 'name' => t('Double curly right'));
    $punctuation['single_curly_left']  = array('value' => '‘', 'name' => t('Single curly left'));
    $punctuation['single_curly_right'] = array('value' => '’', 'name' => t('Single curly right'));
    $punctuation['word-doc-hyphen'] = array('value' => '–', 'name' => t('Word Doc Hyphen'));
}
?>