<?php
/**
 * Implements hook_wysiwyg_plugin().
 */
 
function ckeditor_youtube_wysiwyg_plugin($editor, $version) {
    $plugins = array();
    if ($editor == 'ckeditor' && version_compare($version, '4.0', '>=')) {
        $plugins['youtube'] = array(
            'url' => 'http://ckeditor.com/addon/youtube',
            'buttons' => array(
            'Youtube' => t('Youtube'),
            ),
            'options' => array(
             'youtube_width' => '640',
             'youtube_height' => '480',
             'youtube_related' => FALSE,
             'youtube_older' => FALSE,
             'youtube_privacy' => FALSE,
            ),
            'load' => TRUE,
            'internal' => TRUE,
        );

        $plugins['iframe'] = array(
            'url' => 'http://ckeditor.com/addon/iframe',
            'buttons' => array(
                'IframeUpload' => t('Iframe Upload'),
            ),
            'load' => TRUE,
            'internal' => TRUE,
        );

  }
  return $plugins;
}
?>